# TASK 2: Data Cleansing

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import string
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords

In [2]:
# load the dataset
reviews_df = pd.read_csv('amazon_alexa.tsv', sep='\t')
reviews_df

rating       date         variation  \
0          5  31-Jul-18  Charcoal Fabric    
1          5  31-Jul-18  Charcoal Fabric    
2          4  31-Jul-18    Walnut Finish    
3          5  31-Jul-18  Charcoal Fabric    
4          5  31-Jul-18  Charcoal Fabric    
...      ...        ...               ...   
3145       5  30-Jul-18        Black  Dot   
3146       5  30-Jul-18        Black  Dot   
3147       5  30-Jul-18        Black  Dot   
3148       5  30-Jul-18        White  Dot   
3149       4  29-Jul-18        Black  Dot   

                                       verified_reviews  feedback  
0                                         Love my Echo!         1  
1                                             Loved it!         1  
2     Sometimes while playing a game, you can answer...         1  
3     I have had a lot of fun with this thing. My 4 ...         1  
4                                                 Music         1  
...                                                 ...       ...  
3145  Perfect for kids, adults and everyone in betwe...         1  
3146  Listening to music, searching locations, check...         1  
3147  I do love these things, i have them running my...         1  
3148  Only complaint I have is that the sound qualit...         1  
3149                                               Good         1  

[3150 rows x 5 columns]

In [3]:
# explore the length of the messages
reviews_df['length'] = reviews_df['verified_reviews'].apply(len)
reviews_df.head()

rating       date         variation  \
0       5  31-Jul-18  Charcoal Fabric    
1       5  31-Jul-18  Charcoal Fabric    
2       4  31-Jul-18    Walnut Finish    
3       5  31-Jul-18  Charcoal Fabric    
4       5  31-Jul-18  Charcoal Fabric    

                                    verified_reviews  feedback  length  
0                                      Love my Echo!         1      13  
1                                          Loved it!         1       9  
2  Sometimes while playing a game, you can answer...         1     195  
3  I have had a lot of fun with this thing. My 4 ...         1     172  
4                                              Music         1       5

In [4]:
# drop the date
reviews_df = reviews_df.drop(['date', 'rating', 'length'],axis=1)
reviews_df

variation                                   verified_reviews  \
0     Charcoal Fabric                                       Love my Echo!   
1     Charcoal Fabric                                           Loved it!   
2       Walnut Finish   Sometimes while playing a game, you can answer...   
3     Charcoal Fabric   I have had a lot of fun with this thing. My 4 ...   
4     Charcoal Fabric                                               Music   
...                ...                                                ...   
3145        Black  Dot  Perfect for kids, adults and everyone in betwe...   
3146        Black  Dot  Listening to music, searching locations, check...   
3147        Black  Dot  I do love these things, i have them running my...   
3148        White  Dot  Only complaint I have is that the sound qualit...   
3149        Black  Dot                                               Good   

      feedback  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
3145         1  
3146         1  
3147         1  
3148         1  
3149         1  

[3150 rows x 3 columns]

In [5]:
# avoid dummy variable trap which occurs when one variable can be predicted from the other
variation_dummies = pd.get_dummies(reviews_df['variation'], drop_first = True)
variation_dummies

Black  Dot  Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0              0            0            0            0                 1   
1              0            0            0            0                 1   
2              0            0            0            0                 0   
3              0            0            0            0                 1   
4              0            0            0            0                 1   
...          ...          ...          ...          ...               ...   
3145           1            0            0            0                 0   
3146           1            0            0            0                 0   
3147           1            0            0            0                 0   
3148           0            0            0            0                 0   
3149           1            0            0            0                 0   

      Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                                0                     0            0   
1                                0                     0            0   
2                                0                     0            0   
3                                0                     0            0   
4                                0                     0            0   
...                            ...                   ...          ...   
3145                             0                     0            0   
3146                             0                     0            0   
3147                             0                     0            0   
3148                             0                     0            0   
3149                             0                     0            0   

      Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                     0               0      0           0            0   
1                     0               0      0           0            0   
2                     0               1      0           0            0   
3                     0               0      0           0            0   
4                     0               0      0           0            0   
...                 ...             ...    ...         ...          ...   
3145                  0               0      0           0            0   
3146                  0               0      0           0            0   
3147                  0               0      0           0            0   
3148                  0               0      0           1            0   
3149                  0               0      0           0            0   

      White  Show  White  Spot  
0               0            0  
1               0            0  
2               0            0  
3               0            0  
4               0            0  
...           ...          ...  
3145            0            0  
3146            0            0  
3147            0            0  
3148            0            0  
3149            0            0  

[3150 rows x 15 columns]

In [6]:
# drop the column
reviews_df.drop(['variation'], axis=1, inplace=True)

# add the encoded column again
reviews_df = pd.concat([reviews_df, variation_dummies], axis=1)

reviews_df

verified_reviews  feedback  Black  Dot  \
0                                         Love my Echo!         1           0   
1                                             Loved it!         1           0   
2     Sometimes while playing a game, you can answer...         1           0   
3     I have had a lot of fun with this thing. My 4 ...         1           0   
4                                                 Music         1           0   
...                                                 ...       ...         ...   
3145  Perfect for kids, adults and everyone in betwe...         1           1   
3146  Listening to music, searching locations, check...         1           1   
3147  I do love these things, i have them running my...         1           1   
3148  Only complaint I have is that the sound qualit...         1           0   
3149                                               Good         1           1   

      Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0               0            0            0                 1   
1               0            0            0                 1   
2               0            0            0                 0   
3               0            0            0                 1   
4               0            0            0                 1   
...           ...          ...          ...               ...   
3145            0            0            0                 0   
3146            0            0            0                 0   
3147            0            0            0                 0   
3148            0            0            0                 0   
3149            0            0            0                 0   

      Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                                0                     0            0   
1                                0                     0            0   
2                                0                     0            0   
3                                0                     0            0   
4                                0                     0            0   
...                            ...                   ...          ...   
3145                             0                     0            0   
3146                             0                     0            0   
3147                             0                     0            0   
3148                             0                     0            0   
3149                             0                     0            0   

      Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                     0               0      0           0            0   
1                     0               0      0           0            0   
2                     0               1      0           0            0   
3                     0               0      0           0            0   
4                     0               0      0           0            0   
...                 ...             ...    ...         ...          ...   
3145                  0               0      0           0            0   
3146                  0               0      0           0            0   
3147                  0               0      0           0            0   
3148                  0               0      0           1            0   
3149                  0               0      0           0            0   

      White  Show  White  Spot  
0               0            0  
1               0            0  
2               0            0  
3               0            0  
4               0            0  
...           ...          ...  
3145            0            0  
3146            0            0  
3147            0            0  
3148            0            0  
3149            0            0  

[3150 rows x 17 columns]

In [7]:
# define a pipeline to remove punctuation and stopwords
def message_cleaning(message):
    # remove punctuation
    Test_punc_removed = [char for char in message if char not in string.punctuation]
    Test_punc_removed_join = ''.join(Test_punc_removed)
    # remove stopwords
    Test_punc_removed_join_clean = [word for word in Test_punc_removed_join.split() if word.lower() not in stopwords.words('english')]
    return Test_punc_removed_join_clean

In [8]:
# test the newly added function
reviews_df_clean = reviews_df['verified_reviews'].apply(message_cleaning)

 # show the cleaned up version
print(reviews_df_clean[3]) # show the cleaned up version

['lot', 'fun', 'thing', '4', 'yr', 'old', 'learns', 'dinosaurs', 'control', 'lights', 'play', 'games', 'like', 'categories', 'nice', 'sound', 'playing', 'music', 'well']


In [9]:
print(reviews_df['verified_reviews'][3]) # show the original version

I have had a lot of fun with this thing. My 4 yr old learns about dinosaurs, i control the lights and play games like categories. Has nice sound when playing music as well.


In [10]:
reviews_df_clean

0                                            [Love, Echo]
1                                                 [Loved]
2       [Sometimes, playing, game, answer, question, c...
3       [lot, fun, thing, 4, yr, old, learns, dinosaur...
4                                                 [Music]
                              ...                        
3145                    [Perfect, kids, adults, everyone]
3146    [Listening, music, searching, locations, check...
3147    [love, things, running, entire, home, TV, ligh...
3148    [complaint, sound, quality, isnt, great, mostl...
3149                                               [Good]
Name: verified_reviews, Length: 3150, dtype: object

In [11]:
# Define the cleaning pipeline we defined earlier
vectorizer = CountVectorizer(analyzer = message_cleaning)
reviews_countvectorizer = vectorizer.fit_transform(reviews_df['verified_reviews'])

In [12]:
print(vectorizer.get_feature_names())

['072318', '1', '10', '100', '1000', '100X', '1010', '1030pm', '11', '1100sf', '1220', '129', '12am', '15', '150', '19', '1964', '1990s', '1990’s', '1GB', '1rst', '1st', '2', '20', '200', '2000', '2017', '2030', '229', '23', '2448', '247', '24GHZ', '24ghz', '25', '29', '299', '2999', '2Original', '2nd', '2or', '2package', '3', '30', '300', '30so', '334', '34', '342nd', '3434', '34A34', '34Alexa', '34Alexa34', '34Certified', '34Computer34', '34Dot34', '34Drop', '34First', '34Hub', '34I', '34Im', '34NEVER', '34Philips', '34Play', '34Second', '34Skills34', '34Tell', '34The', '34Things', '34Thongs', '34Try', '34Whats', '34alexa34', '34card34', '34cycle', '34cycle34', '34fixes34', '34fun34', '34group34', '34hear34', '34hmm', '34hmmm', '34it34', '34late', '34learn', '34light34', '34lights34', '34listen34', '34minor', '34outlet34', '34personal34', '34she34', '34show', '34smart', '34smart34', '34sorry', '34spying34', '34the', '34thick34', '34things', '34this', '34trouble', '34try', '34turn', '

In [13]:
print(reviews_countvectorizer.toarray())  

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
reviews_countvectorizer.shape

(3150, 5211)

In [15]:
reviews_df

verified_reviews  feedback  Black  Dot  \
0                                         Love my Echo!         1           0   
1                                             Loved it!         1           0   
2     Sometimes while playing a game, you can answer...         1           0   
3     I have had a lot of fun with this thing. My 4 ...         1           0   
4                                                 Music         1           0   
...                                                 ...       ...         ...   
3145  Perfect for kids, adults and everyone in betwe...         1           1   
3146  Listening to music, searching locations, check...         1           1   
3147  I do love these things, i have them running my...         1           1   
3148  Only complaint I have is that the sound qualit...         1           0   
3149                                               Good         1           1   

      Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0               0            0            0                 1   
1               0            0            0                 1   
2               0            0            0                 0   
3               0            0            0                 1   
4               0            0            0                 1   
...           ...          ...          ...               ...   
3145            0            0            0                 0   
3146            0            0            0                 0   
3147            0            0            0                 0   
3148            0            0            0                 0   
3149            0            0            0                 0   

      Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                                0                     0            0   
1                                0                     0            0   
2                                0                     0            0   
3                                0                     0            0   
4                                0                     0            0   
...                            ...                   ...          ...   
3145                             0                     0            0   
3146                             0                     0            0   
3147                             0                     0            0   
3148                             0                     0            0   
3149                             0                     0            0   

      Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                     0               0      0           0            0   
1                     0               0      0           0            0   
2                     0               1      0           0            0   
3                     0               0      0           0            0   
4                     0               0      0           0            0   
...                 ...             ...    ...         ...          ...   
3145                  0               0      0           0            0   
3146                  0               0      0           0            0   
3147                  0               0      0           0            0   
3148                  0               0      0           1            0   
3149                  0               0      0           0            0   

      White  Show  White  Spot  
0               0            0  
1               0            0  
2               0            0  
3               0            0  
4               0            0  
...           ...          ...  
3145            0            0  
3146            0            0  
3147            0            0  
3148            0            0  
3149            0            0  

[3150 rows x 17 columns]

In [16]:
# drop the column
reviews_df.drop(['verified_reviews'], axis=1, inplace=True)
reviews = pd.DataFrame(reviews_countvectorizer.toarray())

In [17]:
# Now let's concatenate them together
reviews_df = pd.concat([reviews_df, reviews], axis=1)
reviews_df

feedback  Black  Dot  Black  Plus  Black  Show  Black  Spot  \
0            1           0            0            0            0   
1            1           0            0            0            0   
2            1           0            0            0            0   
3            1           0            0            0            0   
4            1           0            0            0            0   
...        ...         ...          ...          ...          ...   
3145         1           1            0            0            0   
3146         1           1            0            0            0   
3147         1           1            0            0            0   
3148         1           0            0            0            0   
3149         1           1            0            0            0   

      Charcoal Fabric   Configuration: Fire TV Stick  Heather Gray Fabric   \
0                    1                             0                     0   
1                    1                             0                     0   
2                    0                             0                     0   
3                    1                             0                     0   
4                    1                             0                     0   
...                ...                           ...                   ...   
3145                 0                             0                     0   
3146                 0                             0                     0   
3147                 0                             0                     0   
3148                 0                             0                     0   
3149                 0                             0                     0   

      Oak Finish   Sandstone Fabric   ...  5201  5202  5203  5204  5205  5206  \
0               0                  0  ...     0     0     0     0     0     0   
1               0                  0  ...     0     0     0     0     0     0   
2               0                  0  ...     0     0     0     0     0     0   
3               0                  0  ...     0     0     0     0     0     0   
4               0                  0  ...     0     0     0     0     0     0   
...           ...                ...  ...   ...   ...   ...   ...   ...   ...   
3145            0                  0  ...     0     0     0     0     0     0   
3146            0                  0  ...     0     0     0     0     0     0   
3147            0                  0  ...     0     0     0     0     0     0   
3148            0                  0  ...     0     0     0     0     0     0   
3149            0                  0  ...     0     0     0     0     0     0   

      5207  5208  5209  5210  
0        0     0     0     0  
1        0     0     0     0  
2        0     0     0     0  
3        0     0     0     0  
4        0     0     0     0  
...    ...   ...   ...   ...  
3145     0     0     0     0  
3146     0     0     0     0  
3147     0     0     0     0  
3148     0     0     0     0  
3149     0     0     0     0  

[3150 rows x 5227 columns]

In [18]:
reviews_df.to_csv("reviews_df")